#!/usr/bin/env node

const fs = require('fs');
const util = require('util');

environment = process.argv[2]
operation = process.argv[3]
parameters = process.argv[4]

if (operation == "Catalog") {
  var data = fs.readFileSync('catalog.json');
  console.log(data.toString());
}

if (operation == "Provision") {
  var obj = JSON.parse(parameters); 
  console.log(obj.id);
}

if (operation == "Poll") {
  var obj = JSON.parse(parameters); 
  var data = {
    "state": "succeeded",
    "description": util.format("An example service instance %s is provisioned.", obj.id)
  }
  console.log(JSON.stringify(data));
}
if (operation == "Deprovision") {
  dummy();
}

if (operation == "Bind") {
  dummy();
}

if (operation == "Unbind") {
  dummy();
}

function dummy() {
  for(var i = 0; i < 100; i++) {
  }
}
